spring.application.name=Ecommorse
spring.datasource.url=jdbc:postgresql://localhost:5432/Ecommerce_Application
spring.datasource.username=postgres
spring.datasource.password=ecommerce123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret-key=VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9yRWNvbW1lcmNl
jwt.issuer=ecommerce-app
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=strict


logging.level.org.springframework.security=INFO
google.recaptcha.secret=6LfeEQEtAAAAAJzNsd2RRLOoCzKgWj7utCJBtT4h
